# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95982d7493bcb78933beda546fef617d474f40487e4dc360e62421936cf8f90d0d354868757356bf7167fa1ffec2bc1307db45e162f13aac1385ff4d076637b0

test:
  secret_key_base: 85cc86f0b98f5ca8aa05fc6976560a38b35a132e69fd846386c51786a6271a4cc5b587653432c18837347e842f6a260171295c270c9fa8364fc2d1b32f8d4cd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
